### ISSUE TITLE
[Proposal] Expose Scrollbar customization from RawScrollbar to Searchfield

### ISSUE THREAD

**Issue by LincolnJota** [maheshmnj/searchfield#99]
**Is your feature request related to a problem? Please describe.**
I was disappointed, as a package as good as this one can't change the color of the scrollbar thumb, but it can change its visibility.
I noticed that in the code there is a RawScrollbar that has the ThumbColor property, and by default it doesn't follow the theme, its default color is a fixed color, as it says here in the official documentation: https://api.flutter.dev/flutter/widgets/RawScrollbar/thumbColor.html

**Describe the solution you'd like**
I'd like to move that property from the RawScrollbar widget to the SearchField widget.

**Comment by maheshmnj** [comment]
Hello @LincolnJota, Thanks for filing the issue. Scrollbars definitely needs customization.

**Comment by maheshmnj** [comment]
Closing as fixed in https://github.com/maheshmnj/searchfield/pull/101
available in the new release [v0.8.5](https://pub.dev/packages/searchfield/changelog)

**Comment by LincolnJota** [comment]
Great, @maheshmnj ! But we still have a problem. The scroll bar shows two scroll bars, correct? I think you get the idea. To fix this scroll bar, you need to hide scrolling from the ListView, I did it here and it worked fine.

You can fix it like this:

in [this line](https://github.com/maheshmnj/searchfield/blob/57e21c82ba24e1c7eb70fc105bba64306513abed/lib/src/searchfield.dart#L545C34-L545C34) you can wrap the ListView to look like this:


```dart
child: RawScrollbar(
    // other configs....
    child: ScrollConfiguration(
      behavior: ScrollConfiguration.of(context).copyWith(scrollbars: false),
      child: listView,
    ),
),
```

That way, we're left with only the scroll we need. Hugs!

**Comment by maheshmnj** [comment]
Oh yes, that should be an easy fix.

**Comment by maheshmnj** [comment]
fixed in https://github.com/maheshmnj/searchfield/pull/102 available in v0.8.6
